export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";

export const GET_FEEDBACK_START = "GET_FEEDBACK_START";
export const GET_FEEDBACK_FAIL = "GET_FEEDBACK_FAIL";
export const GET_FEEDBACK_SUCCESS = "GET_FEEDBACK_SUCCESS";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const CREATE_COURSE_START = "CREATE_COURSE_START";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";

export const GET_COURSES_LIST_START = "GET_COURSES_LIST_START";
export const GET_COURSES_LIST_FAIL = "GET_COURSES_LIST_FAIL";
export const GET_COURSES_LIST_SUCCESS = "GET_COURSES_LIST_SUCCESS";

export const GET_COURSE_DETAIL_START = "GET_COURSE_DETAIL_START";
export const GET_COURSE_DETAIL_FAIL = "GET_COURSE_DETAIL_FAIL";
export const GET_COURSE_DETAIL_SUCCESS = "GET_COURSE_DETAIL_SUCCESS";

export const GET_GRADES_LIST_START = "GET_GRADES_LIST_START";
export const GET_GRADES_LIST_FAIL = "GET_GRADES_LIST_FAIL";
export const GET_GRADES_LIST_SUCCESS = "GET_GRADES_LIST_SUCCESS";

export const GET_COURSE_STATS_START = "GET_COURSE_STATS_START";
export const GET_COURSE_STATS_FAIL = "GET_COURSE_STATS_FAIL";
export const GET_COURSE_STATS_SUCCESS = "GET_COURSE_STATS_SUCCESS";

export const GET_ASSIGNMENT_STATS_START = "GET_ASSIGNMENT_STATS_START";
export const GET_ASSIGNMENT_STATS_FAIL = "GET_ASSIGNMENT_STATS_FAIL";
export const GET_ASSIGNMENT_STATS_SUCCESS = "GET_ASSIGNMENT_STATS_SUCCESS";

export const GET_STAFF_START = "GET_STAFF_START";
export const GET_STAFF_FAIL = "GET_STAFF_FAIL";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";


export const GET_ANNOUNCEMENT_LIST_START = "GET_ANNOUNCEMENT_LIST_START";
export const GET_ANNOUNCEMENTS_LIST_FAIL = "GET_ANNOUNCEMENTS_LIST_FAIL";
export const GET_ANNOUNCEMENTS_LIST_SUCCESS = "GET_ANNOUNCEMENTS_LIST_SUCCESS";

export const GET_ANNOUNCEMENT_DETAIL_START = "GET_ANNOUNCEMENT_DETAIL_START";
export const GET_ANNOUNCEMENT_DETAIL_FAIL = "GET_ANNOUNCEMENT_DETAIL_FAIL";
export const GET_ANNOUNCEMENT_DETAIL_SUCCESS = "GET_ANNOUNCEMENT_DETAIL_SUCCESS";

export const CREATE_ANNOUNCEMENT_START = "CREATE_ANNOUNCEMENT_START";
export const CREATE_ANNOUNCEMENT_FAIL = "CREATE_ANNOUNCEMENT_FAIL";
export const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";

export const MESSAGE_START = "MESSAGE_START";
export const MESSAGE_FAIL = "MESSAGE_FAIL";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";

export const GET_MESSAGE_DETAIL_START = "GET_MESSAGE_DETAIL_START";
export const GET_MESSAGE_DETAIL_FAIL = "GET_MESSAGE_DETAIL_FAIL";
export const GET_MESSAGE_DETAIL_SUCCESS = "GET_MESSAGE_DETAIL_SUCCESS";


export const GET_INBOX_START = "GET_INBOX_START";
export const GET_INBOX_FAIL = "GET_INBOX_FAIL";
export const GET_INBOX_SUCCESS = "GET_INBOX_SUCCESS";

export const GET_OUTBOX_START = "GET_OUTBOX_START";
export const GET_OUTBOX_FAIL = "GET_OUTBOX_FAIL";
export const GET_OUTBOX_SUCCESS = "GET_OUTBOX_SUCCESS";

export const GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS";

export const GET_TA_CHECK = "GET_TA_CHECK";
export const GENERATE_OTP_MAIL = "GENERATE_OTP_MAIL";
